tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

filter:
    excluded_paths:
        - tests/*

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
