name: "CS"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  coding-standards:
    name: "CS Fixer (PHP ${{ matrix.php }})"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php:
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: composer:v2
          ini-values: "date.timezone=Europe/Paris"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"

      - name: "Run PHP CS Fixer"
        run: "vendor/bin/php-cs-fixer fix --verbose --dry-run"

      - name: "Install PHPUnit for PHPStan"
        run: "php vendor/bin/simple-phpunit install"

      - name: "Run PHPStan"
        run: "php vendor/bin/phpstan analyse --no-progress"
